spring.datasource.url=jdbc:mysql://stock-management-db.cx68yckg4xv6.ap-south-2.rds.amazonaws.com:3306/stockdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Msivakumar2000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Changed from update to none ? tables already exist from our import
# update would try to alter tables on every restart ? unnecessary and risky
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Keep Liquibase disabled ? we imported data manually
spring.liquibase.enabled=false

jwt.secret=StockManagementSuperSecretKey2026!!
jwt.expiration=86400000

server.address=0.0.0.0
server.port=8080


spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.root=WARN
logging.level.com.stockmanagement=INFO